# interger
print("*********************** Integer ******************")
print("{}".format(10))
print("{} {}".format(10, 20))
print("{0}".format(10))
print("{0} {1}".format(10, 20))
print("{1} {0}".format(10, 20))
print("{num1}".format(num1=10))
print("{num1} {num2}".format(num1=10, num2=20))
print("{num2} {num1}".format(num1=10, num2=20))

print("++++++++++++++++++++++++++ String ++++++++++++++++++++++++++++++++++++++++++++")
print("{}".format("Yuvraj"))
print("{} {}".format("yuvrj","bagale"))
print("{0} {0}".format("yuvrj","bagale"))
print("{1} {0}".format("yuvrj","bagale"))
print("{str1} {str2}".format(str1="yuvrj",str2="bagale"))
print("{str2} {str1}".format(str1="yuvrj",str2="bagale"))
print("i am from {}. i love cupcakes from {}!".format("india", "india"))
print("i am from {0}. i love cupcakes from  {0}!".format("india"))